container:                         "containers/puntseq.simg"
#container: "shub://hexmek/container:puntseq"
samples:                           "docs/samples.csv"

porechop:
    threads     :                  8
    memory    :                    120000
    check_reads:                   50000


filtlong:
    memory    :                    8000
    min_len :                      1000

filter_length:
    memory    :                    2000
    min_len :                      1400
    max_len :                      1600


stats:
    threads     :                  2
    memory    :                    8000

map:
    threads     :                  1
    memory    :                    50000

plot:
    memory    :                    32000


build_centrifuge_db:
    threads:                       16
    memory:                        250000

centrifuge:
    threads     :                  16
    memory    :                    64000


centrifuge_16s:
    threads     :                  16
    memory    :                    16000


build_centrifuge_16s_db:
    threads     :                  16
    memory    :                    14000


download_kraken2_db:
    threads     :                  16
    memory    :                    20000


build_kraken2_db:
    threads     :                  32
    memory    :                    40000


build_kraken2_16s_db:
    threads     :                  32
    memory    :                    4000


kraken2_classify:
    threads     :                  32
    memory    :                    120000


kraken2_16s_classify:
    threads     :                  16
    memory    :                    3000


build_bracken_db:
    threads     :                  8
    memory    :                    120000
    read_length:                   1450
    kmer_length:                   35


build_bracken_16s_db:
    threads     :                  16
    memory    :                    3000
    read_length:                   1450
    kmer_length:                   35


build_bracken_16s_db_k21:
    threads     :                  16
    memory    :                    3000
    read_length:                   1450
    kmer_length:                   21


bracken:
    memory    :                    500
    read_length:                   1450
    threshold:                     2
